# Note: comments for symbols refer to the class name of Nerd Fonts
# Starship version support: 1.14.2
"$schema" = 'https://starship.rs/config-schema.json'

### Generic prompt configurations
scan_timeout = 30                                                                                          # default = 30
command_timeout = 500                                                                                      # default = 500
add_newline = false                                                                                         # Don't print a new line before the start of the prompt
continuation_prompt = "[](bg:color_background_base fg:color_base_orange)[](fg:color_background_base)"
palette = "coffee"                                                                                         # select the color palette to be used

format = """\
    ([](bg:color_foreground_dark fg:color_background_base)$shell[](bg:color_background_base fg:color_foreground_dark))\
    ([](bg:color_base_red_light fg:color_background_base)$sudo[](bg:color_background_base fg:color_base_red_light))\
    ([](bg:color_base_red_light fg:color_background_base)${custom.root}[](bg:color_background_base fg:color_base_red_light))\
    ([](bg:color_username fg:color_background_base)${custom.ssh_user}[](bg:color_background_base fg:color_username))\
    ([](bg:color_base_red_light fg:color_background_base)${custom.ssh_root}[](bg:color_background_base fg:color_base_red_light))\
    ([](bg:color_hostname fg:color_background_base)${custom.ssh_host}[](bg:color_background_base fg:color_hostname))\
    ([](bg:color_username fg:color_background_base)$username[](bg:color_background_base fg:color_username))\
    ([](bg:color_hostname fg:color_background_base)$hostname[](bg:color_background_base fg:color_hostname))\
    (↓ Styling of the directory module is handled in the module section ↓)\
    (($directory))\
    (↓ Container modules ↓)\
    ([](bg:color_docker fg:color_background_base)$docker_context[](bg:color_background_base fg:color_docker))\
    ([](bg:color_container fg:color_background_base)$container[](bg:color_background_base fg:color_container))\
    (↑ Container modules ↑)\
    (↓ Toolchain version modules ↓)\
    ([](bg:color_dotnet fg:color_background_base)$dotnet[](bg:color_background_base fg:color_dotnet))\
    ([](bg:color_dotnet fg:color_background_base)${custom.dotnetUnitTest}[](bg:color_background_base fg:color_dotnet))\
    ([](bg:color_nodejs fg:color_background_base)$nodejs[](bg:color_background_base fg:color_nodejs))\
    ([](bg:color_python fg:color_background_base)$python[](bg:color_background_base fg:color_python))\
    (↑ Toolchain version modules ↑)\
    (↓ Package modules ↓)\
    ([](bg:color_memory fg:color_background_base)$package[](bg:color_background_base fg:color_memory))\
    (↑ Package modules ↑)\
    ([](bg:color_memory fg:color_background_base)$memory_usage[](bg:color_background_base fg:color_memory))\
    ([](bg:color_env_var fg:color_background_base)${env_var.FIRST}[](bg:color_background_base fg:color_env_var))\
    (↑ above input line ↑)\
    (\
        [](bg:none fg:color_background_base)\
        $line_break\
    )\
    (↓ on input line ↓)\
    ($localip)\
    ($cmd_duration)\
    ($shlvl)\
    ($jobs)\
    ($status)\
    ($character)\
"""

right_format = """\
    (\
        [](bg:none fg:color_base_blue)[](bg:color_base_blue fg:color_background_base)\
        ([](bg:color_background_base fg:color_git_branch)${custom.giturl}(bg:color_git_branch fg:color_background_base))\
        ([](bg:color_background_base fg:color_git_branch)$git_branch[](bg:color_git_branch fg:color_background_base))\
        ([](bg:color_git_branch fg:color_git_commit)$git_commit[](bg:color_git_commit fg:color_background_base))\
        ([](bg:color_background_base fg:color_git_status)$git_status[](bg:color_git_status fg:color_background_base))\
        ([](bg:color_background_base fg:color_git_state)$git_state[](bg:color_git_state fg:color_background_base))\
        ([](bg:color_background_base fg:color_git_metrics)$git_metrics[](bg:color_git_metrics fg:color_background_base))\
        ([](bg:color_background_base fg:color_base_red_light)$battery[](bg:color_base_red_light fg:color_background_base))\
        ([](bg:color_background_base fg:color_time)$time[](bg:color_time fg:color_background_base))\
    )\
"""
## Generic prompt configurations
[character]
success_symbol = "[](bg:color_base_blue fg:color_background_base)[](fg:color_base_blue)"
error_symbol = "[](bg:color_base_red fg:color_background_base)[](fg:color_base_red)"
# vicmd_symbol = "[](bg:color_background_base fg:color_base_blue)[  ](bold bg:color_base_blue fg:color_foreground_dark)[](bg:color_base_blue fg:color_foreground_dark)"
vimcmd_visual_symbol = "[](bg:color_background_base fg:color_base_yellow)[  ](bold bg:color_base_yellow fg:color_foreground_dark)[](bg:color_base_yellow fg:color_foreground_dark)"
vimcmd_replace_symbol = "[](bg:color_background_base fg:color_base_orange)[  ](bold bg:color_base_orange fg:color_foreground_dark)[](bg:color_base_orange fg:color_foreground_dark)"
vimcmd_replace_one_symbol = "[](bg:color_background_base fg:color_base_orange)[  ](bold bg:color_base_orange fg:color_foreground_light)[](bg:color_base_orange fg:color_foreground_dark)"
format = "$symbol"

[line_break]
disabled = true

[directory]
home_symbol = " " # nf-seti-home
# home_symbol = "󰮧" # nf-md-home_variant_outline
# home_symbol = "" # nf-oct-home
# home_symbol = "" # nf-cod-home
read_only = " "                                                                           # nf-fa-lock
style = "italic bg:color_directory fg:color_foreground_light"
read_only_style = "bg:color_base_red fg:color_foreground_light"
before_repo_root_style = "italic bg:color_directory_repo_before fg:color_foreground_light"
repo_root_style = "italic bold bg:color_directory fg:color_foreground_light"
# truncate_to_repo = false
truncation_length = 4    # default = 3
truncation_symbol = "… " # default = ""
# fish_style_pwd_dir_length = 3 # default = 0
# use_logical_path = false
# use_os_path_sep = false
format = "([](bg:color_base_red fg:color_background_base)[$read_only]($read_only_style)[](bg:color_background_base fg:color_base_red))[](bg:color_directory fg:color_background_base)[$path]($style)[](bg:color_background_base fg:color_directory)"
repo_root_format = """\
    ([](bg:color_base_red fg:color_background_base)[$read_only]($read_only_style)[](bg:color_background_base fg:color_base_red))\
    [](bg:color_directory fg:color_background_base)\
    [$repo_root]($repo_root_style)\
    [$path]($style)\
    [](bg:color_background_base fg:color_directory)\
"""
[username]
format = "[($user)](fg:color_foreground_light bg:color_directory)"  # replace with your actual colors

[hostname]
style = "bg:color_ssh_connection fg:color_foreground_light"  # replace with your actual style
format = "[( $hostname)]($style)"

[nodejs]
symbol = "💩"
style = "bg:color_nodejs fg:color_foreground_light"
format = "[$symbol($version )]($style)"

[dotnet]
symbol = "\ue77f"
style = "bg:color_dotnet fg:color_foreground_light"
heuristic = true
detect_extensions = ["csproj", "fsproj", "xproj", "sln"]
format = "[$symbol.Net($version)]($style)"

[python]
symbol = "\U000f0320"
style = "bg:color_python fg:color_foreground_dark"
python_binary = ["python3", "python", "python2"]
format = "[${symbol}(${pyenv_prefix}${version})(\\($virtualenv\\))]($style)"

[shell]
bash_indicator = "\\$_"
fish_indicator = ""
zsh_indicator = "%_"
powershell_indicator = "\ue683"
ion_indicator = "(\\$_)"
elvish_indicator = "\U000f0627"
tcsh_indicator = "\U000f01e5 "
nu_indicator = "[\U000f096d](fg:color_base_blue)"
xonsh_indicator = "🐚"
cmd_indicator = "\uebc4"
unknown_indicator = "\uf059 "
style = "bg:color_foreground_dark fg:color_foreground_light"
format = "[$indicator]($style)"

[custom.dotnetUnitTest]
description = "Display if project is for Unit Tests"
symbol = "✔"
style = "bg:color_dotnet"
when = "/Users/noahspielman/.config/StarShipScripts/dotnetUnitTestCheck.sh"
format = "[$symbol]($style)"

[custom.giturl]
disabled = true
description = "Display icon for remote Git server"
command = """
    GIT_REMOTE=$(command git ls-remote --get-url 2> /dev/null)
    if [[ "$GIT_REMOTE" =~ "github" ]]; then
        # GIT_REMOTE_SYMBOL="" # nf-cod-github_inverted
        GIT_REMOTE_SYMBOL="" # nf-fa-github
    elif [[ "$GIT_REMOTE" =~ "gitlab" ]]; then
        GIT_REMOTE_SYMBOL="" # nf-fa-gitlab
    elif [[ "$GIT_REMOTE" =~ "bitbucket" ]]; then
        GIT_REMOTE_SYMBOL="" # nf-fa-bitbucket
    elif [[ "$GIT_REMOTE" =~ "git" ]]; then
        GIT_REMOTE_SYMBOL="" # nf-fa-git_square
    else
        GIT_REMOTE_SYMBOL="󰊢 " # nf-md-git
        # GIT_REMOTE_SYMBOL="" # nf-fa-unlink
        # GIT_REMOTE_SYMBOL="󰜛" # nf-md-source_commit_local
    fi
    echo "$GIT_REMOTE_SYMBOL "
"""
require_repo = true
when = true
shell = ["bash", "--noprofile", "--norc"]
format = "[$output ](bg:color_git_branch fg:color_foreground_dark)"

[git_branch]
# disabled = true
symbol = "" # nf-oct-git_branch
# symbol = "󰊢 " # nf-md-git
style = "bg:color_git_branch fg:color_foreground_dark"
# always_show_remote = true
# truncation_length = 4 # default = 9223372036854775807
# truncation_symbol = "" # default = "…"
# only_attached = true
# ignore_branches = ["main", "master"]
format = "[$symbol $branch(:$remote_name)]($style)"
## other variables:
##   remote_branch = The name of the branch tracked on remote_name

[git_commit]
# disabled = true
style = "bg:color_git_commit fg:color_foreground_dark"
commit_hash_length = 4                                 # default = 7
# only_detached = false
tag_disabled = false
tag_symbol = "󰓹 "    # nf-md-tag
# tag_max_candidates = 0
format = "[ $hash $tag]($style)" #  = nf-fa-hashtag

[git_metrics]
# disabled = false
added_style = 'bg:color_git_metrics fg:color_foreground_light'
deleted_style = 'bg:color_git_metrics fg:color_foreground_light'
# only_nonzero_diffs = false
# format = '([󰺪 $added]($added_style))([ 󰺨 $deleted]($deleted_style))' # 󰺪 = nf-md-text_box_plus // 󰺨 = nf-md-text_box_minus
format = '([󰺪 ](bg:color_git_metrics fg:color_git_metrics_added)[$added]($added_style))([ 󰺨 ](bg:color_git_metrics fg:color_git_metrics_deleted)[$deleted]($deleted_style))' # 󰺪 = nf-md-text_box_plus // 󰺨 = nf-md-text_box_minus

[git_state]
# disabled = true
style = "bg:color_git_state fg:color_foreground_dark"
rebase = "rebasing"
merge = "merging"
revert = "reverting"
cherry_pick = " picking"                                      # nf-fae-cherry
bisect = "bisecting"
am = "am'ing"
am_or_rebase = "am/rebase"
format = '[$state($progress_current/$progress_total)]($style)'

[git_status]
# disabled = true
style = "bg:color_git_status fg:color_foreground_dark"
staged = " ${count}"                                  # nf-fa-check
modified = "  ${count}"                               # nf-fa-edit
# modified = "  ${count}" # nf-fa-pencil
renamed = "󰗧 ${count}"    # nf-md-cursor_text
untracked = "  ${count}" # nf-fa-question
deleted = "  ${count}"   # nf-fa-remove
conflicted = " ${count}" # nf-fa-flag
stashed = "  ${count}"   # nf-fa-bank
# stashed = "  ${count}" # nf-fa-inbox
up_to_date = ""
ahead = "󰞙 ${count}"                          # nf-md-arrow_expand_up
behind = "󰞖 ${count}"                         # nf-md-arrow_expand_down
diverged = "󰡏 ${ahead_count} ${behind_count}" # nf-md-arrow_expand_vertical
# diverged = "󰯎 ${ahead_count} ${behind_count}" # nf-md-swap_vertical_bold
# ignore_submodules = true
format = "[($staged$modified$renamed$untracked$deleted$conflicted$stashed$ahead_behind )]($style)"

[battery]
disabled = false
full_symbol = "󰁹"                       # nf-md-battery
charging_symbol = "󱊥 "                  # nf-md-battery_charging_medium
discharging_symbol = "󱊡"                # nf-md-battery_low
unknown_symbol = "󰂑"                    # nf-md-battery_unknown
empty_symbol = "󰂎"                      # nf-md-battery_outline
format = "[$symbol$percentage]($style)"
[[battery.display]]
threshold = 10
style = "bold bg:color_base_red_light fg:color_foreground_light"
[[battery.display]]
threshold = 20
style = "bg:color_base_red_light fg:color_foreground_dark"
[[battery.display]] # uncomment this section to always see your battery information
threshold = 100
style = "bg:color_base_red_light fg:color_foreground_light"

[custom.ssh_connection]
description = "Indicates when connected via SSH"
command = "echo $SSH_CONNECTION"
when = "env:SSH_CONNECTION"
style = "bg:color_ssh_connection fg:color_foreground_light"
symbol = ""
format = "[$symbol]($style)](bg:color_background_base fg:color_ssh_connection)"

[palettes.pastel]
## Generics -- editor
color_foreground_light = "#f7e6d9"
color_foreground_dark = "#b5a9b9"
color_background_base = "#f0d4d4"
color_directory = "#e0c1e8"
color_directory_repo_before = "#c7bdc3"
color_hostname = "#fad8bb"
color_username = "#a9cfff"
color_base_blue = "#d7effa"
color_base_magenta = "#e6ccff"
color_base_orange = "#ffdfc7"
color_base_red = "#f7b3b0"
color_base_red_light = "#ffcec2"
color_base_red_dark = "#d89f92"
color_base_yellow = "#fff7cc"

## Specifics
## General colors
color_os = "#f7ffb1"          # soft yellow
color_env_var = "#d0d0d0"      # soft gray
color_memory = "#d0d0d0"      # soft gray
color_shell_level = "#fff7cc"  # soft yellow
color_time = "#ffdfc7"        # soft orange
color_vimcmd = "#bfb5bd"      # soft purple

## Container colors
color_container = "#d4a8d9"    # soft purple
color_docker = "#accfdd"      # soft blue

## Source control colors
color_git_branch = "#d9f4cb"           # soft green
color_git_commit = "#f5d9d2"           # soft pink
color_git_metrics = "#bfb5bd"          # soft purple
color_git_metrics_added = "#d0f0d1"    # soft green
color_git_metrics_deleted = "#f7b3b0"   # soft red
color_git_state = "#f5d9d2"            # soft pink
color_git_status = "#f7e3b2"           # soft yellow
color_vcsh = "#9a8f98"                 # soft dark gray

## SSH Colors
color_ssh_connection = "#f9ccd5"       # soft pink

## Toolchain version
color_dotnet = "#b8b2d6"               # soft purple
color_nodejs = "#c7f3c7"               # soft green
color_python = "#f7eeba"               # soft yellow

## Configuration shell modules
color_guix = "#f7d6a2"                 # soft yellow
color_nix = "#8f9ab5"                  # soft blue-gray

[palettes.dull]
## Generics -- editor
color_foreground_light = "#f5f1e8"  # Cream
color_foreground_dark = "#4e453f"   # Espresso
color_background_base = "#8c7a6e"   # Latte
color_directory = "#9c8b7c"         # Mocha
color_directory_repo_before = "#736359"  # Cappuccino
color_hostname = "#c0a890"          # Macchiato
color_username = "#6f5e54"          # Coffee Bean
color_base_blue = "#b8a58f"         # Iced Coffee
color_base_magenta = "#a99585"      # Americano
color_base_orange = "#bfa283"       # Frappuccino
color_base_red = "#a3816b"          # Ristretto
color_base_red_light = "#c0a38b"    # Cortado
color_base_red_dark = "#8c7363"     # Lungo
color_base_yellow = "#d4c3a5"       # Flat White

## Specifics
## General colors
color_os = "#dacbb1"                # Café au Lait
color_env_var = "#ccc1b4"           # Brewed
color_memory = "#ccc1b4"            # Brewed
color_shell_level = "#d4c3a5"       # Flat White
color_time = "#bfa283"              # Frappuccino
color_vimcmd = "#9c8b7c"            # Mocha

## Container colors
color_container = "#a78f7e"         # Irish Coffee
color_docker = "#b9a89b"            # Cold Brew

## Source control colors
color_git_branch = "#c1b6a1"        # Coffee with Milk
color_git_commit = "#d1c3b0"        # Latte Art
color_git_metrics = "#9c8b7c"       # Mocha
color_git_metrics_added = "#b5a893" # Café Bombón
color_git_metrics_deleted = "#a3816b" # Ristretto
color_git_state = "#d1c3b0"         # Latte Art
color_git_status = "#dacbb1"        # Café au Lait
color_vcsh = "#6b5e54"              # Dark Roast

## SSH Colors
color_ssh_connection = "#d3c1ad"    # Caramel Macchiato

## Toolchain version
color_dotnet = "#a89b8f"           # Vienna Coffee
color_nodejs = "#bcb09e"           # White Coffee
color_python = "#d1c4a8"           # Affogato

## Configuration shell modules
color_guix = "#d3c2ae"             # Turkish Coffee
color_nix = "#7c6f63"              # Coffee Grounds

[palettes.coffee]
## Generics -- editor
color_foreground_light = "#ffebd2"
color_foreground_dark = "#5a3825"
color_background_base = "#6f4a37"
color_directory = "#8a5d4a"
color_directory_repo_before = "#a5715d"
color_hostname = "#c08471"
color_username = "#db9884"
color_base_blue = "#e7ab98"
color_base_magenta = "#f3bfab"
color_base_orange = "#ffccbf"
color_base_red = "#ffd9d2"
color_base_red_light = "#ffe6e6"
color_base_red_dark = "#fff2f2"
color_base_yellow = "#ffffff"

## Specifics
## General colors
color_os = "#f7d9c5"
color_env_var = "#f0cbb2"
color_memory = "#e8be9f"
color_shell_level = "#e1b08c"
color_time = "#d9a279"
color_vimcmd = "#d19566"
color_container = "#ca8753"
color_docker = "#c27a40"
color_git_branch = "#bb6c2d"
color_git_commit = "#b35f1a"
color_git_metrics = "#ab5207"
color_git_metrics_added = "#a34600"
color_git_metrics_deleted = "#9b3a00"
color_git_state = "#932e00"
color_git_status = "#dacbb1"
color_vcsh = "#ffffff"
color_ssh_connection = "#e7ab98"
color_dotnet = "#733d00"
color_nodejs = "#745640"
color_python = "#7e3333"
color_guix = "#c08471"
color_nix = "#5a3825"
